//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBandTour.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conciertos
    {
        public int ConciertoID { get; set; }
        public int BandaID { get; set; }
        public string FechaConcierto { get; set; }
        public string HoraConcierto { get; set; }
        public string Pais { get; set; }
        public string Direccion { get; set; }
    
        public virtual Bandas Bandas { get; set; }
    }
}
