//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBandTour.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyBandTourEntities2 : DbContext
    {
        public MyBandTourEntities2()
            : base("name=MyBandTourEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bandas> Bandas { get; set; }
        public virtual DbSet<Conciertos> Conciertos { get; set; }
    
        public virtual int sp_CrearConcierto(Nullable<int> bandaID, string fechaConcierto, string horaConcierto, string pais, string direccion)
        {
            var bandaIDParameter = bandaID.HasValue ?
                new ObjectParameter("BandaID", bandaID) :
                new ObjectParameter("BandaID", typeof(int));
    
            var fechaConciertoParameter = fechaConcierto != null ?
                new ObjectParameter("FechaConcierto", fechaConcierto) :
                new ObjectParameter("FechaConcierto", typeof(string));
    
            var horaConciertoParameter = horaConcierto != null ?
                new ObjectParameter("HoraConcierto", horaConcierto) :
                new ObjectParameter("HoraConcierto", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("Pais", pais) :
                new ObjectParameter("Pais", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CrearConcierto", bandaIDParameter, fechaConciertoParameter, horaConciertoParameter, paisParameter, direccionParameter);
        }
    
        public virtual int sp_EliminarConcierto(Nullable<int> conciertoID)
        {
            var conciertoIDParameter = conciertoID.HasValue ?
                new ObjectParameter("ConciertoID", conciertoID) :
                new ObjectParameter("ConciertoID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_EliminarConcierto", conciertoIDParameter);
        }
    
        public virtual int sp_ModificarConcierto(Nullable<int> conciertoID, Nullable<int> bandaID, string fechaConcierto, string horaConcierto, string pais, string direccion)
        {
            var conciertoIDParameter = conciertoID.HasValue ?
                new ObjectParameter("ConciertoID", conciertoID) :
                new ObjectParameter("ConciertoID", typeof(int));
    
            var bandaIDParameter = bandaID.HasValue ?
                new ObjectParameter("BandaID", bandaID) :
                new ObjectParameter("BandaID", typeof(int));
    
            var fechaConciertoParameter = fechaConcierto != null ?
                new ObjectParameter("FechaConcierto", fechaConcierto) :
                new ObjectParameter("FechaConcierto", typeof(string));
    
            var horaConciertoParameter = horaConcierto != null ?
                new ObjectParameter("HoraConcierto", horaConcierto) :
                new ObjectParameter("HoraConcierto", typeof(string));
    
            var paisParameter = pais != null ?
                new ObjectParameter("Pais", pais) :
                new ObjectParameter("Pais", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ModificarConcierto", conciertoIDParameter, bandaIDParameter, fechaConciertoParameter, horaConciertoParameter, paisParameter, direccionParameter);
        }
    
        public virtual ObjectResult<sp_VerConciertos_Result> sp_VerConciertos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_VerConciertos_Result>("sp_VerConciertos");
        }
    }
}
